Tutorial 03

#Part 1-Google Colab and Python
##1. Create a new notebook and code the following

In [1]:
import numpy as np

###1. Create a numpy array of size 2 x 2

In [2]:
n1 = np.array([[1, 2], [3, 4]])
print(n1)

[[1 2]
 [3 4]]


###2. Create a random numpy array of size 3 x 4

In [3]:
n2 = np.random.random((3, 4))
print(n2)

[[0.38175745 0.80046436 0.71575079 0.27224695]
 [0.84662213 0.64484546 0.3115101  0.37226999]
 [0.1306141  0.36018781 0.00336119 0.06132355]]


###3. Create a numpy array of ones and a numpy array of zeros

In [4]:
n3a = np.ones((2, 2))
print(n3a)

[[1. 1.]
 [1. 1.]]


In [5]:
n3b = np.zeros((2, 2))
print(n3b)

[[0. 0.]
 [0. 0.]]


###4. Create a random numpy array of size 6 x 3 and transpose it

In [6]:
n4 = np.random.random((6, 3))
print(n4)

[[0.73733437 0.7695695  0.14502519]
 [0.47527839 0.33045604 0.45772524]
 [0.5118821  0.8316631  0.65649962]
 [0.38761465 0.67638492 0.44064582]
 [0.38037002 0.36687113 0.26880405]
 [0.14703502 0.30708847 0.51900916]]


In [7]:
n4_transpose = n4.T
print(n4_transpose)

[[0.73733437 0.47527839 0.5118821  0.38761465 0.38037002 0.14703502]
 [0.7695695  0.33045604 0.8316631  0.67638492 0.36687113 0.30708847]
 [0.14502519 0.45772524 0.65649962 0.44064582 0.26880405 0.51900916]]


###5. Create two random numpy array of size n x p and p x m and then compute the dot product

In [8]:
n = 2
p = 3
m = 4
n5a = np.random.random((n, p))
print("Array (n x p): \n", n5a)
n5b = np.random.random((p, m))
print("Array (p x m): \n", n5b)
dot_product = np.dot(n5a, n5b)
print("Dot product: \n", dot_product)

Array (n x p): 
 [[0.70578685 0.51256134 0.88655447]
 [0.44586002 0.16358486 0.44647611]]
Array (p x m): 
 [[0.78712352 0.13711289 0.67359933 0.28332829]
 [0.84590245 0.6750076  0.36261784 0.83341672]
 [0.03793934 0.3054622  0.91591235 0.03754265]]
Dot product: 
 [[1.02275361 0.71356414 1.47328761 0.66043017]
 [0.50626275 0.30793575 0.76858277 0.27942101]]


#Part 2-Colab and github
## From Google Colab, push the notebook onto your GitHub