<a href="https://colab.research.google.com/github/shaoern0606/data-science-toolkit/blob/main/Tutorial03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tutorial 03

#Part 1-Google Colab and Python
##1. Create a new notebook and code the following

In [1]:
import numpy as np

###1. Create a numpy array of size 2 x 2

In [2]:
n1 = np.array([[1, 2], [3, 4]])
print(n1)

[[1 2]
 [3 4]]


###2. Create a random numpy array of size 3 x 4

In [3]:
n2 = np.random.random((3, 4))
print(n2)

[[0.15601408 0.70929519 0.48683382 0.81636646]
 [0.14065172 0.43748514 0.11888054 0.60559925]
 [0.13112216 0.36133998 0.94563723 0.52164077]]


###3. Create a numpy array of ones and a numpy array of zeros

In [4]:
n3a = np.ones((2, 2))
print(n3a)

[[1. 1.]
 [1. 1.]]


In [5]:
n3b = np.zeros((2, 2))
print(n3b)

[[0. 0.]
 [0. 0.]]


###4. Create a random numpy array of size 6 x 3 and transpose it

In [6]:
n4 = np.random.random((6, 3))
print(n4)

[[0.88089275 0.93232358 0.43181054]
 [0.90700797 0.82202772 0.83660409]
 [0.5180082  0.37809479 0.95271196]
 [0.8431407  0.68626175 0.04078181]
 [0.98393475 0.14772141 0.56978775]
 [0.71068442 0.91632426 0.23217817]]


In [7]:
n4_transpose = n4.T
print(n4_transpose)

[[0.88089275 0.90700797 0.5180082  0.8431407  0.98393475 0.71068442]
 [0.93232358 0.82202772 0.37809479 0.68626175 0.14772141 0.91632426]
 [0.43181054 0.83660409 0.95271196 0.04078181 0.56978775 0.23217817]]


###5. Create two random numpy array of size n x p and p x m and then compute the dot product

In [8]:
n = 2
p = 3
m = 4
n5a = np.random.random((n, p))
print("Array (n x p): \n", n5a)
n5b = np.random.random((p, m))
print("Array (p x m): \n", n5b)
dot_product = np.dot(n5a, n5b)
print("Dot product: \n", dot_product)

Array (n x p): 
 [[0.56203937 0.15627542 0.65436246]
 [0.25171676 0.1124668  0.82721924]]
Array (p x m): 
 [[0.05469676 0.31169893 0.06112233 0.30113616]
 [0.83819138 0.12667173 0.5715166  0.77862976]
 [0.04086629 0.24533146 0.9577578  0.45711871]]
Dot product: 
 [[0.1884718  0.35551844 0.7503879  0.59005239]
 [0.14184217 0.29564911 0.87193784 0.54150841]]


#Part 2-Colab and github
## From Google Colab, push the notebook onto your GitHub