Tutorial 03

#Part 1-Google Colab and Python
##1. Create a new notebook and code the following

In [1]:
import numpy as np

###1. Create a numpy array of size 2 x 2

In [2]:
n1 = np.array([[1, 2], [3, 4]])
print(n1)

[[1 2]
 [3 4]]


###2. Create a random numpy array of size 3 x 4

In [3]:
n2 = np.random.random((3, 4))
print(n2)

[[0.00279424 0.95895823 0.95557259 0.83537145]
 [0.47077926 0.80298952 0.28626847 0.10089428]
 [0.04197529 0.3204386  0.86662949 0.00412464]]


###3. Create a numpy array of ones and a numpy array of zeros

In [4]:
n3a = np.ones((2, 2))
print(n3a)

[[1. 1.]
 [1. 1.]]


In [5]:
n3b = np.zeros((2, 2))
print(n3b)

[[0. 0.]
 [0. 0.]]


###4. Create a random numpy array of size 6 x 3 and transpose it

In [6]:
n4 = np.random.random((6, 3))
print(n4)

[[0.83006205 0.09925961 0.9179502 ]
 [0.50352857 0.21976618 0.49053907]
 [0.80934067 0.74609721 0.32244506]
 [0.23894744 0.56048769 0.92357678]
 [0.83893516 0.60851385 0.26057357]
 [0.07484181 0.88301278 0.99902799]]


In [7]:
n4_transpose = n4.T
print(n4_transpose)

[[0.83006205 0.50352857 0.80934067 0.23894744 0.83893516 0.07484181]
 [0.09925961 0.21976618 0.74609721 0.56048769 0.60851385 0.88301278]
 [0.9179502  0.49053907 0.32244506 0.92357678 0.26057357 0.99902799]]


###5. Create two random numpy array of size n x p and p x m and then compute the dot product

In [8]:
n = 2
p = 3
m = 4
n5a = np.random.random((n, p))
print("Array (n x p): \n", n5a)
n5b = np.random.random((p, m))
print("Array (p x m): \n", n5b)
dot_product = np.dot(n5a, n5b)
print("Dot product: \n", dot_product)

Array (n x p): 
 [[0.84728183 0.31437959 0.99548947]
 [0.23069816 0.51401755 0.17851532]]
Array (p x m): 
 [[0.01300505 0.90460335 0.02611519 0.03422922]
 [0.6257761  0.40103893 0.62476891 0.10010914]
 [0.06081431 0.61841261 0.1733491  0.28685794]]
Dot product: 
 [[0.26829018 1.50815568 0.39110873 0.34603813]
 [0.33551642 0.52522751 0.35811238 0.11056301]]
